version: '3.8'

services:
  app:
    image: kirananarayanak/healthslot-app:latest
    container_name: healthslot-app-staging
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=staging
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/healthslot-staging
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - healthslot-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: healthslot-mongodb-staging
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_staging_data:/data/db
    networks:
      - healthslot-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  healthslot-network:
    driver: bridge

volumes:
  mongodb_staging_data: 