version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    network_mode: host
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--httpPort=8081
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true

volumes:
  jenkins-data:

networks:
  jenkins-network:
    driver: bridge 