apiVersion: v1
kind: ConfigMap
metadata:
  name: healthslot-config
  namespace: staging
data:
  NODE_ENV: "staging"
  PORT: "3000"
  MONGODB_URI: "mongodb://mongodb:27017/healthslot"
  JWT_SECRET: "your-staging-secret"
  JWT_EXPIRE: "24h"
