apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-staging
  namespace: staging
spec:
  serviceName: mongodb-staging
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      environment: staging
  template:
    metadata:
      labels:
        app: mongodb
        environment: staging
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-staging
  namespace: staging
spec:
  selector:
    app: mongodb
    environment: staging
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None 