apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthslot-production
  namespace: production
  labels:
    app: healthslot
    env: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthslot
      env: production
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: healthslot
        env: production
    spec:
      containers:
      - name: healthslot
        image: healthslot:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: healthslot-config-production
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: healthslot-service-production
  namespace: production
spec:
  selector:
    app: healthslot
    env: production
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer 