apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-production
  namespace: production
spec:
  serviceName: mongodb-service
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
      env: production
  template:
    metadata:
      labels:
        app: mongodb
        env: production
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: production
spec:
  selector:
    app: mongodb
    env: production
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None 